//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class tclass_schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tclass_schedule()
        {
            this.tclass_reserve = new HashSet<tclass_reserve>();
            this.tcourse_photo = new HashSet<tcourse_photo>();
        }
    
        public int class_schedule_id { get; set; }
        public int class_id { get; set; }
        public int coach_id { get; set; }
        public int field_id { get; set; }
        public System.DateTime course_date { get; set; }
        public int course_time_id { get; set; }
        public int Max_student { get; set; }
        public int class_status_id { get; set; }
        public decimal class_payment { get; set; }
        public bool coach_payment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tclass_reserve> tclass_reserve { get; set; }
        public virtual tclass_status_detail tclass_status_detail { get; set; }
        public virtual tclasses tclasses { get; set; }
        public virtual tfield tfield { get; set; }
        public virtual tIdentity tIdentity { get; set; }
        public virtual ttimes_detail ttimes_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcourse_photo> tcourse_photo { get; set; }
    }
}
