//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class tclasses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tclasses()
        {
            this.tclass_schedule = new HashSet<tclass_schedule>();
            this.tcoach_expert = new HashSet<tcoach_expert>();
        }
    
        public int class_id { get; set; }
        public Nullable<int> class_sort1_id { get; set; }
        public Nullable<int> class_sort2_id { get; set; }
        public string class_name { get; set; }
        public string class_introduction { get; set; }
        public int limited_gender { get; set; }
        public string class_photo { get; set; }
        public bool class_status { get; set; }
    
        public virtual tclass_limit_details tclass_limit_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tclass_schedule> tclass_schedule { get; set; }
        public virtual tclass_sort_有氧 tclass_sort_有氧 { get; set; }
        public virtual tclass_sort_訓練 tclass_sort_訓練 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcoach_expert> tcoach_expert { get; set; }
    }
}
