//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class tcoach_expert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tcoach_expert()
        {
            this.tcoach_photo = new HashSet<tcoach_photo>();
        }
    
        public int expert_id { get; set; }
        public int coach_id { get; set; }
        public int class_id { get; set; }
    
        public virtual tclasses tclasses { get; set; }
        public virtual tIdentity tIdentity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcoach_photo> tcoach_photo { get; set; }
    }
}
