//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class tfield
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tfield()
        {
            this.tclass_schedule = new HashSet<tclass_schedule>();
            this.tfield_reserve = new HashSet<tfield_reserve>();
            this.tfield_photo = new HashSet<tfield_photo>();
        }
    
        public int field_id { get; set; }
        public int Gym_id { get; set; }
        public string floor { get; set; }
        public string field_name { get; set; }
        public decimal field_payment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tclass_schedule> tclass_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tfield_reserve> tfield_reserve { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tfield_photo> tfield_photo { get; set; }
        public virtual tGym tGym { get; set; }
    }
}
