//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGym
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGym()
        {
            this.tfield = new HashSet<tfield>();
        }
    
        public int Gym_id { get; set; }
        public int region_id { get; set; }
        public string address { get; set; }
        public string e_mail { get; set; }
        public string phone { get; set; }
        public string website { get; set; }
        public string photo { get; set; }
        public bool status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tfield> tfield { get; set; }
        public virtual tregion_table tregion_table { get; set; }
    }
}
