//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class tIdentity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tIdentity()
        {
            this.tclass_reserve = new HashSet<tclass_reserve>();
            this.tclass_schedule = new HashSet<tclass_schedule>();
            this.tcoach_expert = new HashSet<tcoach_expert>();
            this.tcoach_info_id = new HashSet<tcoach_info_id>();
            this.tfield_reserve = new HashSet<tfield_reserve>();
            this.tmember_follow = new HashSet<tmember_follow>();
        }
    
        public int id { get; set; }
        public int role_id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string e_mail { get; set; }
        public string password { get; set; }
        public string photo { get; set; }
        public System.DateTime birthday { get; set; }
        public string address { get; set; }
        public int gender_id { get; set; }
        public bool activated { get; set; }
        public Nullable<decimal> payment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tclass_reserve> tclass_reserve { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tclass_schedule> tclass_schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcoach_expert> tcoach_expert { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tcoach_info_id> tcoach_info_id { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tfield_reserve> tfield_reserve { get; set; }
        public virtual tgender_Table tgender_Table { get; set; }
        public virtual tidentity_role_detail tidentity_role_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmember_follow> tmember_follow { get; set; }
    }
}
