//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjGym
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmember_follow
    {
        public int follow_id { get; set; }
        public int member_id { get; set; }
        public int coach_id { get; set; }
        public int status_id { get; set; }
        public Nullable<decimal> stars { get; set; }
        public string describe { get; set; }
    
        public virtual tIdentity tIdentity { get; set; }
        public virtual tmember_status_details tmember_status_details { get; set; }
    }
}
